apiVersion: v1
kind: Pod
metadata:
  name: libvirt-sidecar-example
spec:
  hostNetwork: true
  containers:
    - name: libvirt
      image: docker.io/djzager/libvirt:latest
      imagePullPolicy: Always
      securityContext:
        privileged: true
    - name: libvirt-client
      image: docker.io/djzager/libvirt-client:latest
      imagePullPolicy: Always
      command:
        - /usr/bin/virt-install
      args:
        - --connect
        - qemu+tcp://127.0.0.1/system
        - --name
        - centos7
        - --ram
        - "1024"
        - --disk
        - path=./centos7.qcow2,size=8
        - --vcpus
        - "1"
        - --os-type
        - linux
        - --os-variant
        - centos7.0
        - --network
        - bridge=br0
        - --graphics
        - "none"
        - --console
        - "pty,target_type=serial"
        - --location
        - 'http://mirror.i3d.net/pub/centos/7/os/x86_64/'
        - --extra-args
        - 'console=ttyS0,115200n8 serial'
      securityContext:
        privileged: true
