apiVersion: v1
kind: Pod
metadata:
  name: baremetal-install
spec:
  hostNetwork: true
  containers:
    - name: libvirt
      # libvirt image that creates provisioning|baremetal libvirt networks
      image: docker.io/djzager/libvirt:netstart
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        # To share the cached image between installer and libvirt container
        - name: image-cache
          mountPath: /output
    - name: installer
      # baremetal installer from registry.svc.ci.openshift.org/ocp/release:4.3.0-0.ci-2019-11-22-122829
      # TODO: figure out how to get ci pull secrets into CRC VM
      image: docker.io/djzager/installer:libvirt
      imagePullPolicy: Always
      command:
        - /usr/bin/openshift-install
      args:
        - create
        - cluster
        - --log-level
        - debug
        - --dir
        - /ocp
      securityContext:
        privileged: true
      volumeMounts:
        - name: image-cache
          mountPath: /output
        - name: ocp-dir
          mountPath: /ocp
  initContainers:
    # need this so there are not a ton of symlinks in the config directory when running the installer
    - name: copy-config
      image: busybox
      command: ['sh', '-c', 'cp /ocp-config/* /deploy-config/* /openshift-config/* /manifests-config/* /ocp']
      volumeMounts:
        - name: ocp-dir
          mountPath: /ocp
        - name: ocp-config
          mountPath: /ocp-config
        - name: deploy-config
          mountPath: /deploy-config
        - name: openshift-config
          mountPath: /openshift-config
        - name: manifests-config
          mountPath: /manifests-config
  volumes:
    - name: ocp-dir
      emptyDir: {}
    - name: image-cache
      emptyDir: {}
    - name: ocp-config
      configMap:
        name: ocp
    - name: deploy-config
      configMap:
        name: deploy
    - name: openshift-config
      configMap:
        name: openshift
    - name: manifests-config
      configMap:
        name: manifests
