apiVersion: v1
kind: Pod
metadata:
  name: baremetal-install
spec:
  hostNetwork: true
  containers:
    - name: libvirt
      # libvirt image that creates provisioning|baremetal libvirt networks
      image: docker.io/djzager/libvirt:netstart
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        # To share the cached image between installer and libvirt container
        - name: image-cache
          mountPath: /output
    - name: installer
      image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2d0cb0f49dc4f3e99a9b571967ee3f8710fc57c68b858b51ea99a24dd230dcd1
      imagePullPolicy: Always
      command:
        - /usr/bin/openshift-install
      args:
        - create
        - cluster
        - --log-level
        - debug
        - --dir
        - /ocp
      env:
        - name: OPENSHIFT_RELEASE_IMAGE
          value: "registry.svc.ci.openshift.org/ocp/release:4.3.0-0.nightly-2019-12-03-032607"
      securityContext:
        privileged: true
      volumeMounts:
        - name: image-cache
          mountPath: /output
        - name: ocp-dir
          mountPath: /ocp
  initContainers:
    # need this so there are not a ton of symlinks in the config directory when running the installer
    - name: copy-config
      image: busybox
      command: ['sh', '-c', 'cp /ocp-config/* /deploy-config/* /openshift-config/* /manifests-config/* /ocp']
      volumeMounts:
        - name: ocp-dir
          mountPath: /ocp
        - name: ocp-config
          mountPath: /ocp-config
        - name: deploy-config
          mountPath: /deploy-config
        - name: openshift-config
          mountPath: /openshift-config
        - name: manifests-config
          mountPath: /manifests-config
  volumes:
    - name: ocp-dir
      emptyDir: {}
    - name: image-cache
      emptyDir: {}
    - name: ocp-config
      configMap:
        name: ocp
    - name: deploy-config
      configMap:
        name: deploy
    - name: openshift-config
      configMap:
        name: openshift
    - name: manifests-config
      configMap:
        name: manifests
